org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.defaults.buildfeatures.buildconfig=true
android.enableJetifier=true
org.gradle.java.home=C:\\Program Files\\Java\\jdk-17

org.gradle.jvmargs=-Xmx2048m

org.gradle.wrapper.networkTimeout=60000

org.gradle.wrapper.networkTimeout=120000

org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
